services:

  redis:
    image: redis:7-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  vector-db:
    image: qdrant/qdrant:v1.11.3
    restart: always
    volumes:
      - vector-db-data:/var/lib/qdrant/data
    environment:
      - QDRANT_DATA_PATH=/var/lib/qdrant/data
      - QDRANT_GRPC_PORT=6333
      - QDRANT_HTTP_PORT=6333

    ports:
      - "6333:6333"

  backend:
    build:
      context: ./backend

    restart: always

    depends_on:
      vector-db:
        condition: service_started
        restart: true
      redis:
        condition: service_healthy
        restart: true

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - tmp:/tmp

    environment:
      - QDRANT_URL=http://vector-db:6333
      - CELERY__BROKER_URL=redis://redis:6379/1
      - CELERY__RESULT_BACKEND=redis://redis:6379/2

    ports:
      - "8001:8001"

  worker:
    build:
      context: ./backend
    command: celery -A app.worker worker --loglevel=info
    restart: always
    depends_on:
      backend:
        condition: service_started
        restart: true

    volumes:
      - tmp:/tmp

    environment:
      - QDRANT_URL=http://vector-db:6333
      - CELERY__BROKER_URL=redis://redis:6379/1
      - CELERY__RESULT_BACKEND=redis://redis:6379/2

volumes:
  vector-db-data:
  tmp:
